GET http://localhost:3000

###

GET http://localhost:3000/device

###

GET http://localhost:3000/device/645139e893b940e0ef824495

###

POST http://localhost:3000/device
Content-Type: application/json

{
  "name": "TP012",
  "description": "Sensor of temperature room 203 CIVT",
  "engUnit": "ºC"
}

###

DELETE http://localhost:3000/device/645139e893b940e0ef824495

###

PUT http://localhost:3000/device/6451392993b940e0ef824491
Content-Type: application/json

{
  "name": "TP011",
  "description": "Sensor of temperature room 204 CIVT",
  "engUnit": "ºF"
}