version: "3.9"
services:
  web:
    build: .
    ports:
      - "3000:3000"
    restart: always
    depends_on:
      - mongodb
    environment:
      NODE_ENV: production
      DB_URL: mongodb://mongodb:27017/iot
  mongodb:
    image: "mongo:4.2"
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db
volumes:
  mongodb_data: